import { Pool } from 'pg';
export async function bootstrapDatabase(pool: Pool): Promise<void> {
  await pool.query(`
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE TABLE IF NOT EXISTS tenants (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),name VARCHAR(200) NOT NULL UNIQUE,slug VARCHAR(100) NOT NULL UNIQUE,plan VARCHAR(50) NOT NULL DEFAULT 'enterprise',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,email VARCHAR(255) NOT NULL,name VARCHAR(200) NOT NULL,role VARCHAR(50) NOT NULL DEFAULT 'LOGISTICS_EXEC',password_hash VARCHAR(255),mfa_secret VARCHAR(100),mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,last_login TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,email));
    CREATE TABLE IF NOT EXISTS user_permissions (user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,permission VARCHAR(100) NOT NULL,PRIMARY KEY(user_id,permission));
    CREATE TABLE IF NOT EXISTS audit_logs (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID REFERENCES tenants(id),user_id UUID REFERENCES users(id),user_name VARCHAR(200),action VARCHAR(100) NOT NULL,detail TEXT,ip_address INET,risk_level VARCHAR(20) NOT NULL DEFAULT 'low',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS warehouses (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),name VARCHAR(200) NOT NULL,city VARCHAR(100) NOT NULL,state VARCHAR(100),capacity_sqm NUMERIC(10,2),type VARCHAR(50) NOT NULL DEFAULT 'general',lat NUMERIC(10,6),lng NUMERIC(10,6),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS vendors (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),name VARCHAR(200) NOT NULL,gstin VARCHAR(15),email VARCHAR(255),phone VARCHAR(20),address TEXT,payment_terms INTEGER NOT NULL DEFAULT 30,rating NUMERIC(3,2) NOT NULL DEFAULT 3.00,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS inventory (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),sku VARCHAR(100) NOT NULL,name VARCHAR(255) NOT NULL,qty INTEGER NOT NULL DEFAULT 0,unit VARCHAR(50) NOT NULL DEFAULT 'Units',warehouse_id UUID REFERENCES warehouses(id),unit_cost NUMERIC(12,2) NOT NULL DEFAULT 0,reorder_level INTEGER NOT NULL DEFAULT 50,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(tenant_id,sku));
    CREATE TABLE IF NOT EXISTS inventory_audit (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),sku VARCHAR(100) NOT NULL,delta INTEGER NOT NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS purchase_orders (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),vendor_id UUID NOT NULL REFERENCES vendors(id),po_number VARCHAR(50) NOT NULL UNIQUE,items JSONB NOT NULL DEFAULT '[]',total_value NUMERIC(15,2) NOT NULL DEFAULT 0,status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',expected_date DATE,notes TEXT,approved_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS orders (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),order_number VARCHAR(50) NOT NULL UNIQUE,customer_name VARCHAR(200) NOT NULL,origin_city VARCHAR(100) NOT NULL,dest_city VARCHAR(100) NOT NULL,items JSONB NOT NULL DEFAULT '[]',total_items INTEGER NOT NULL DEFAULT 0,total_value NUMERIC(15,2) NOT NULL DEFAULT 0,weight_kg NUMERIC(10,3),volume_cbm NUMERIC(10,3),status VARCHAR(50) NOT NULL DEFAULT 'PENDING',priority VARCHAR(20) NOT NULL DEFAULT 'standard',sla_date DATE,notes TEXT,created_by UUID,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS order_events (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,event_type VARCHAR(100) NOT NULL,description TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS shipments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),shipment_number VARCHAR(50) NOT NULL UNIQUE,order_id UUID REFERENCES orders(id),carrier_name VARCHAR(200),transport_mode VARCHAR(50) NOT NULL DEFAULT 'Road',vehicle_reg VARCHAR(50),device_id VARCHAR(100),origin_city VARCHAR(100) NOT NULL,dest_city VARCHAR(100) NOT NULL,status VARCHAR(50) NOT NULL DEFAULT 'PENDING',eta TIMESTAMPTZ,departed_at TIMESTAMPTZ,delivered_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS carriers (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),name VARCHAR(200) NOT NULL,code VARCHAR(50),modes TEXT[] NOT NULL DEFAULT '{}',on_time_pct NUMERIC(5,2) NOT NULL DEFAULT 85.00,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS invoices (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),invoice_number VARCHAR(50) NOT NULL UNIQUE,customer_name VARCHAR(200) NOT NULL,order_id UUID REFERENCES orders(id),line_items JSONB NOT NULL DEFAULT '[]',subtotal NUMERIC(15,2) NOT NULL DEFAULT 0,tax_amount NUMERIC(15,2) NOT NULL DEFAULT 0,total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,currency VARCHAR(10) NOT NULL DEFAULT 'INR',status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',due_date DATE,paid_at TIMESTAMPTZ,payment_ref VARCHAR(200),notes TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS payments (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),invoice_id UUID NOT NULL REFERENCES invoices(id),amount NUMERIC(15,2) NOT NULL,currency VARCHAR(10) NOT NULL DEFAULT 'INR',method VARCHAR(50) NOT NULL,status VARCHAR(50) NOT NULL DEFAULT 'PENDING',gateway VARCHAR(50),gateway_txn_id VARCHAR(200),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS notification_templates (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID REFERENCES tenants(id),code VARCHAR(100) NOT NULL UNIQUE,name VARCHAR(200) NOT NULL,channels TEXT[] NOT NULL DEFAULT '{}',subject_tpl TEXT,body_tpl TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS notification_log (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID REFERENCES tenants(id),template_id UUID REFERENCES notification_templates(id),channel VARCHAR(50) NOT NULL,recipient VARCHAR(255) NOT NULL,subject TEXT,body TEXT,status VARCHAR(50) NOT NULL DEFAULT 'SENT',error_msg TEXT,sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS integrations (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id UUID NOT NULL REFERENCES tenants(id),name VARCHAR(200) NOT NULL,type VARCHAR(100) NOT NULL,protocol VARCHAR(50) NOT NULL DEFAULT 'REST',config JSONB NOT NULL DEFAULT '{}',status VARCHAR(50) NOT NULL DEFAULT 'PENDING',last_sync TIMESTAMPTZ,error_msg TEXT,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
    CREATE TABLE IF NOT EXISTS integration_events (id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),integration_id UUID NOT NULL REFERENCES integrations(id),event_type VARCHAR(100) NOT NULL,direction VARCHAR(10) NOT NULL DEFAULT 'IN',payload JSONB,status VARCHAR(50) NOT NULL DEFAULT 'SUCCESS',error_msg TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
  `);
  const{rows}=await pool.query(`SELECT id FROM tenants WHERE slug='demo' LIMIT 1`);
  if(rows.length>0){console.log('[db] Already seeded ✓');return;}
  const T='00000000-0000-0000-0000-000000000001',A='00000000-0000-0000-0000-000000000010';
  await pool.query(`INSERT INTO tenants(id,name,slug,plan)VALUES($1,'TransportOS Demo','demo','enterprise')ON CONFLICT DO NOTHING`,[T]);
  await pool.query(`INSERT INTO users(id,tenant_id,email,name,role,active)VALUES($1,$2,'admin@transportos.com','System Admin','SUPER_ADMIN',TRUE)ON CONFLICT DO NOTHING`,[A,T]);
  for(const[e,n,r]of[['arjun.sharma@transportos.com','Arjun Sharma','OPS_MANAGER'],['priya.nair@transportos.com','Priya Nair','LOGISTICS_EXEC'],['deepa.menon@transportos.com','Deepa Menon','FINANCE_ADMIN']]){await pool.query(`INSERT INTO users(tenant_id,email,name,role,active)VALUES($1,$2,$3,$4,TRUE)ON CONFLICT DO NOTHING`,[T,e,n,r]);}
  for(const[n,c,s,la,lo,ca,ty]of[['Mumbai Central Hub','Mumbai','Maharashtra',19.076,72.877,45000,'general'],['Delhi NCR Distribution','Gurugram','Haryana',28.459,77.026,62000,'general'],['Chennai Port Depot','Chennai','Tamil Nadu',13.082,80.270,38000,'port'],['Bangalore Tech DC','Bangalore','Karnataka',12.971,77.594,28000,'general']]){await pool.query(`INSERT INTO warehouses(tenant_id,name,city,state,lat,lng,capacity_sqm,type)VALUES($1,$2,$3,$4,$5,$6,$7,$8)ON CONFLICT DO NOTHING`,[T,n,c,s,la,lo,ca,ty]);}
  for(const[n,g,e,p,a,t,r]of[['Tata Motors Ltd','27AABCT1234F1ZV','logistics@tata.com','+91-22-6665-8282','Mumbai',30,4.5],['Reliance Industries','27AAACR1234G1ZX','supply@ril.com','+91-22-3555-5000','Mumbai',45,4.2],['Infosys Logistics','29AABCI1234H1ZY','vendors@infosys.com','+91-80-2852-0261','Bangalore',30,4.7]]){await pool.query(`INSERT INTO vendors(tenant_id,name,gstin,email,phone,address,payment_terms,rating)VALUES($1,$2,$3,$4,$5,$6,$7,$8)ON CONFLICT DO NOTHING`,[T,n,g,e,p,a,t,r]);}
  for(const[n,co,m,o]of[['BlueDart','BDE',['Air','Road'],96.2],['Delhivery','DEL',['Road'],88.4],['DTDC','DTC',['Road','Rail'],82.1]]){await pool.query(`INSERT INTO carriers(tenant_id,name,code,modes,on_time_pct)VALUES($1,$2,$3,$4,$5)ON CONFLICT DO NOTHING`,[T,n,co,m,o]);}
  for(const[nu,cu,or,de,ic,va,st]of[['ORD-19283','Tata Motors','Mumbai','Delhi',42,824000,'CONFIRMED'],['ORD-19284','Reliance Retail','Bangalore','Chennai',8,144500,'IN_TRANSIT'],['ORD-19285','Infosys','Pune','Hyderabad',15,320000,'PENDING']]){await pool.query(`INSERT INTO orders(tenant_id,order_number,customer_name,origin_city,dest_city,total_items,total_value,status,priority,created_by)VALUES($1,$2,$3,$4,$5,$6,$7,$8,'standard',$9)ON CONFLICT DO NOTHING`,[T,nu,cu,or,de,ic,va,st,A]);}
  for(const[nu,ca,mo,or,de,st]of[['SHP-2847','BlueDart','Air','Mumbai','Delhi','IN_TRANSIT'],['SHP-2848','DTDC','Road','Chennai','Kolkata','IN_TRANSIT'],['SHP-2849','Gati','Road','Bangalore','Pune','DELAYED']]){await pool.query(`INSERT INTO shipments(tenant_id,shipment_number,carrier_name,transport_mode,origin_city,dest_city,status)VALUES($1,$2,$3,$4,$5,$6,$7)ON CONFLICT DO NOTHING`,[T,nu,ca,mo,or,de,st]);}
  for(const[nu,cu,su,ta,to,st,du]of[['INV-2025-0481','Tata Motors Ltd',482500,86850,569350,'PAID','2025-05-15'],['INV-2025-0480','Reliance Industries',1240000,223200,1463200,'PENDING','2025-05-10']]){await pool.query(`INSERT INTO invoices(tenant_id,invoice_number,customer_name,subtotal,tax_amount,total_amount,currency,status,due_date)VALUES($1,$2,$3,$4,$5,$6,'INR',$7,$8)ON CONFLICT DO NOTHING`,[T,nu,cu,su,ta,to,st,du]);}
  for(const[co,na,ch,su,bo]of[['SHIPMENT_DISPATCHED','Shipment Dispatched',['email','sms','push'],'{{shipment_id}} dispatched','Departed {{origin}}.'],['DELAY_ALERT','Delay Alert',['email','sms','in-app'],'Alert','SLA risk.'],['INVOICE_GENERATED','Invoice Generated',['email'],'Invoice {{invoice_number}}','For {{amount}}.']]){await pool.query(`INSERT INTO notification_templates(tenant_id,code,name,channels,subject_tpl,body_tpl,active)VALUES($1,$2,$3,$4,$5,$6,TRUE)ON CONFLICT DO NOTHING`,[T,co,na,ch,su,bo]);}
  for(const[n,ty,pr]of[['SAP S/4HANA','ERP','RFC/BAPI'],['BlueDart API','Carrier','REST'],['Stripe Billing','Finance','REST']]){await pool.query(`INSERT INTO integrations(tenant_id,name,type,protocol,status,active)VALUES($1,$2,$3,$4,'CONNECTED',TRUE)ON CONFLICT DO NOTHING`,[T,n,ty,pr]);}
  console.log('[db] ✓ Seeded');
}
